version: '3'

services:
  invweb:
    container_name: invweb
    build:
      context: .
    volumes:
      - ./investments:/investments
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    depends_on:
      - invdb


  invdb:
    image: ${PG_BASE_IMAGE}
    container_name: invdb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ${PG_HOST_VOLUME}:${PG_CONTAINER_VOLUME}
    ports:
      - "5432:5432"

volumes:
  pg_inv_data:
