version: '3'

services:
  biweb:
    container_name: biweb
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL_DATALAKE=${DATABASE_URL_DATALAKE}
      - DATABASE_URL_C4UNO=${DATABASE_URL_C4UNO}
      - DATABASE_URL_BI=${DATABASE_URL_BI}
      - LANDBOT_API_TOKEN=${LANDBOT_API_TOKEN}
    stdin_open: true
    tty: true
    depends_on:
      - bidb

  bidb:
    image: ${PG_BASE_IMAGE}
    container_name: bidb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ${PG_HOST_VOLUME}:${PG_CONTAINER_VOLUME}

  proxy:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - biweb

volumes:
  pgdata:
  static_data:
